# .github/workflows/concurrency-example.yml

name: Concurrency Example

on:
  push:
    branches:
      - main

concurrency:
  group: workflow_group_name
  cancel-in-progress: true  # Cancel any in-progress runs if a new run starts

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print message
        run: echo "This workflow is running with concurrency control!"
        
